### ISSUE TITLE
Can you also put it for int?

### ISSUE THREAD

**Issue by Hekhy** [TechnoUrmish/Sizer#12]
I was using it but I got tired of always having to write 18.0.sp if for example I wanted that font size, it is a bit cumbersome, since we normally use round sizes, and although if it must be in double for those cases where we need to be specific, I I would like you to put it also for int, since it would be much more comfortable. Otherwise it works very well, it is a very good job and I thank you.

![hgfdrth](https://user-images.githubusercontent.com/70041483/110253396-66b0a880-7f8a-11eb-9b01-6ec2f401bc27.jpg)

**Comment by CoderUni** [comment]
@Hekhy It seems like the owner is not maintaining the package anymore. I've created a package that solves that issue and supports null safety: https://pub.dev/packages/responsive_sizer

**Comment by Hekhy** [comment]
> @Hekhy Parece que el propietario ya no mantiene el paquete. Creé un paquete que resuelve ese problema y es compatible con la seguridad nula: https://pub.dev/packages/responsive_sizer

**Comment by Hekhy** [comment]
@CoderUni Thank you very much, that's perfect, I will definitely use it, but everything else works the same right?
