### ISSUE TITLE
The method '*' was called on null.

### ISSUE THREAD

**Issue by pratikbutani** [TechnoUrmish/Sizer#15]
Implemented  **sizer: ^1.1.8** but getting error when I set it as following:

`SizedBox(height: 20.0.h),`

Error:

```
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building LoginWithSet(dirty, dependencies: [_FocusMarker, MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#39772]], state: _LoginWithSetState#2e207):
The method '*' was called on null.
Receiver: null
Tried calling: *(20.0)

The relevant error-causing widget was: 
  
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SizerUtil.height (package:sizer/sizer_util.dart:32:20)
#2      SizerExt.h (package:sizer/sizer_ext.dart:7:29)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
...


```

**Comment by fayisode** [comment]
Same issue here.

**Comment by pratikbutani** [comment]
Solved. May you forgot this [lines ](https://github.com/TechnoUrmish/Sizer/blob/master/example/lib/main.dart#L13-L27) to add in main.dart

**Comment by fayisode** [comment]
It's working fine now.

**Comment by harshilishere** [comment]
I have these lines in my main.dart but still getting this error. What is the basic reason for this error!?!!? 
Please someone help. 

`import 'package:flutter/material.dart';
import 'home_page.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,),
      home: HomePage(),
    );
  }
}
`
