### ISSUE TITLE
Package does not support web

### ISSUE THREAD

**Issue by cankush625** [TechnoUrmish/Sizer#17]
Hello,
I have tried using this package for web development using Flutter but it throws an error.  

Code that causes an error: 

`
import 'package:sizer/sizer.dart';

// NavBar constants
double navbarVerticalMargin = 5.0.h;
`

![Screenshot (2549)](https://user-images.githubusercontent.com/41515472/114298615-f3dca500-9ad4-11eb-8bf1-d8d43aa1aed7.png)

Can you please consider adding web and desktop support for this package?
For mobile app development, this is a very useful package.
Thanks.

**Comment by CoderUni** [comment]
This package supports flutter web. It doesn't seem to be maintained anymore though so I created my own package with null safety and extra features: https://pub.dev/packages/responsive_sizer

Also, could you post your entire code?

**Comment by cankush625** [comment]
I will try this package. Thank you!

**Comment by TechnoUrmish** [comment]
Sorry for late response, now sizer is supportting to web in new update  so please check and update package with code
