### ISSUE TITLE
Read Me Version is incorrect

### ISSUE THREAD

**Issue by AndyMeagher** [TechnoUrmish/Sizer#18]
I am unable to use this plugin and get `sizer ^2.0.12 which doesn't match any versions, version solving failed.` when trying to install.

**Comment by calvintam236** [comment]
I think it was just released today per https://pub.dev/packages/sizer/versions.

**Comment by TechnoUrmish** [comment]
Hello @calvintam236 We have resolved this error and thanks to @AndyMeagher and @calvintam236 for use this package  and found this error.
