### ISSUE TITLE
Failed to run - dependency issues

### ISSUE THREAD

**Issue by calvintam236** [TechnoUrmish/Sizer#19]
```
Because no versions of freezed match >0.11.6 <0.12.0 and freezed >=0.1.2 <0.11.6 depends on analyzer ^0.39.4, freezed >=0.1.2 <0.11.6-∞ or >0.11.6 <0.12.0 requires analyzer ^0.39.4.
And because analyzer >=0.32.4 <0.39.5 depends on crypto >=1.1.1 <3.0.0, freezed >=0.1.2 <0.11.6-∞ or >0.11.6 <0.12.0 requires crypto >=1.1.1 <3.0.0 or analyzer ^0.39.5.
And because freezed 0.11.6 depends on analyzer ^0.39.5 which depends on crypto ^2.0.0, freezed >=0.1.2 <0.12.0 requires crypto >=1.1.1 <3.0.0.
And because sizer >=2.0.11 depends on universal_io ^2.0.4 which depends on crypto ^3.0.0, freezed >=0.1.2 <0.12.0 is incompatible with sizer >=2.0.11.
So, because XXXX depends on both sizer ^2.0.12 and freezed ^0.11.2, version solving failed.
Running "flutter pub get" in XXXX...
pub get failed (1; So, because XXXX depends on both sizer ^2.0.12 and freezed ^0.11.2, version solving failed.)
```

Can you please fix it?

**Comment by calvintam236** [comment]
Not sure why my `pubspec` got the `freezed` in the dev dependencies, but after removing it, it will works. Not sure I should close this or not.

**Comment by TechnoUrmish** [comment]
Hello @calvintam236 i think you should update flutter, project and dependency
1. Update flutter to 2.0 (if you have not)
2. Migrate your project to null safety
3. After migration update freezed dependency with latest version and read important note of freezed
![Screenshot 2021-04-28 at 10 37 44 AM](https://user-images.githubusercontent.com/71811481/116349526-d7977280-a80d-11eb-8490-b43f6c2f9bfa.png)

4. Restart you IDE

**Comment by calvintam236** [comment]
Thanks! I think the project was working on was from v1, and when someone merged the new `pubspec` from master, somehow they left the old dependencies there.
