### ISSUE TITLE
Maybe readme typo errors?

### ISSUE THREAD

**Issue by Pistacchione** [TechnoUrmish/Sizer#2]
Hi,

in the readme file there is this example:

```
Container(
      width: 20.0.w,    //It will take a 20% of screen width
      height:30.0.h     //It will take a 20% of screen height
    )
```

maybe there is a typo error and comment for `height: 30.0.h` should be `It will take a 30% of screen height`?

Another question,
`TextStyle(fontSize: 15.0.sp)`, `15.0.sp` is always a percentile of screen width or height?

Thanks!

**Comment by TechnoUrmish** [comment]
> Hi,
> 
> in the readme file there is this example:
> 
> ```
> Container(
>       width: 20.0.w,    //It will take a 20% of screen width
>       height:30.0.h     //It will take a 20% of screen height
>     )
> ```
> 
> maybe there is a typo error and comment for `height: 30.0.h` should be `It will take a 30% of screen height`?
> 
> Another question,
> `TextStyle(fontSize: 15.0.sp)`, `15.0.sp` is always a percentile of screen width or height?
> 
> Thanks!

Thank you Matteo Benin for find issue in my package and yes it is typo error in readme file and .sp method working always a percentile of screen size

**Comment by Pistacchione** [comment]
Great,

Thank you for this very useful package!
