### ISSUE TITLE
method 'ResponsiveSizer' isn't defined for the class

### ISSUE THREAD

**Issue by amarjeetpatidar** [TechnoUrmish/Sizer#24]
Even after importing sizer. dart I am not able to access the ResponsiveSizer.
In Pubspec.yaml

`dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  sizer: ^2.0.13`

Error:
`
Try correcting the name to the name of an existing method, or defining a method named 'ResponsiveSizer'.
    return ResponsiveSizer(
           ^^^^^^^^^^^^^^^`

**Comment by Strime** [comment]
ReadMe is not up to date.
Have a look to https://github.com/TechnoUrmish/Sizer/issues/23 ;)

**Comment by amarjeetpatidar** [comment]
Use Sizer Method instead of ResponsiveSizer.

**Comment by MurtadhaS** [comment]
@amarjeetpatidar the documents should be changed.

**Comment by calvintam236** [comment]
> @amarjeetpatidar the documents should be changed.

Well, need to ask whoever has write access to merge #20..
