### ISSUE TITLE
React to changes of the operating system font size 

### ISSUE THREAD

**Issue by patgdev** [TechnoUrmish/Sizer#3]
The sizer font size function does not react to the font size of the underlying operating system. 

When I increase my system font size, the text is not displayed properly. I guess the `sp`- function needs to interact with `MediaQuery.textScaleFactorOf(context)` or something like this.

**Comment by TechnoUrmish** [comment]
Thank you patgdev for comment but .sp method is working well with system text size in both android and iOS

**Comment by patgdev** [comment]
Thank you for your reply!

Can you tell me why the example underneath is not working when i double the system font size on my device?

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 100.0.w,
          height: 10.0.h,
          child: Text(
            "Font size test by changing system font size",
            style: TextStyle(fontSize: 14.0.sp),
          ),
        ),
      ),
    );
```

The sentence stops after the word _font_ regardless of the orientation. Additionally, the lower part of the letters is also not fully visible (the bottom is somehow cut)
