### ISSUE TITLE
Sizer not working

### ISSUE THREAD

**Issue by samrah135** [TechnoUrmish/Sizer#75]
import 'package:example/screens/home_screen.dart';
import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Sizer(
      builder: (context, orientation, deviceType) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'Sizer',
          theme: ThemeData.light(),
          home: HomeScreen() ,
        );
      },
    );
  }
}

The method 'Sizer' isn't defined for the type 'MyApp'.

**Comment by Prashant4900** [comment]
Repo is not updated use ResponsiveSizer instant of sizer

**Comment by XCarlosEduardoX** [comment]
same :C

**Comment by samrah135** [comment]
> same :C

Repo is not updated use ResponsiveSizer instant of sizer.

**Comment by samrah135** [comment]
> Repo is not updated use ResponsiveSizer instant of sizer

Thanks 👍

**Comment by TechnoPrashant** [comment]
Version 3.0.3
