### ISSUE TITLE
is there any plan to support null-safety?

### ISSUE THREAD

**Issue by rockingdice** [TechnoUrmish/Sizer#9]
Flutter offers the null-safety feature, do you have a plan to support it?

**Comment by rc8marcelo** [comment]
Wanna follow up on this too. Flutter 2 just dropped today and made null safety part of stable

**Comment by fareesh** [comment]
I've submitted a PR #11

**Comment by ZetiMente** [comment]
> I've submitted a PR #11

I looked at your PR and it's just changing the type of a few variables. Is there any sign of life from the @TechnoUrmish ?

**Comment by darmawan01** [comment]
Hopely ready soon, thank guys

**Comment by joshbenaron** [comment]
> Hopely ready soon, thank guys

Hey - Will you publish this?

**Comment by CoderUni** [comment]
@rc8marcelo @fareesh  @darmawan01 @joshbenaron @ZetiMente

It seems like the owner is not maintaining the package anymore. I've created an improved package that supports null safety: https://pub.dev/packages/responsive_sizer

**Comment by rc8marcelo** [comment]
> @rc8marcelo @fareesh @darmawan01 @joshbenaron @ZetiMente
> 
> It seems like the owner is not maintaining the package anymore. I've created an improved package that supports null safety: https://pub.dev/packages/responsive_sizer

Amazing! Wish I could try it now but the app I'm developing still has a package or 2 that needs null safety. I'll try it as soon as I upgrade to 2.0

**Comment by TechnoUrmish** [comment]
Sorry @fareesh @rockingdice @rc8marcelo  @darmawan01 @joshbenaron  for late response, Now sizer has an update with null safety so check and update package
